### ISSUE TITLE
Epic: Provision Project

### ISSUE THREAD

**Issue by bignamehere** [USDA-FPAC/fpac-design-system#1]
- [x] Initialize Repo
- [x] Duplicate Proto for local build
- [x] Pull in new style codebase ("fds-style")
- [x] Update Codebase to remove "FSA" references in Pages
- [x] Develop Structure for codebase
- [x] Add initial GA tracker for GA4

**Comment by bignamehere** [comment]
Closing to open feature specific issues
